# ---------------------------------------------
# Informasi umum
# ---------------------------------------------
title: Kode Profit
description: Belajar. Berbagi. Profit bareng! — Strategi trading, EA, dan edukasi trader modern.
url: "https://kodeprofit.github.io"  # Ganti jika nanti pakai domain custom
baseurl: ""  # Kalau repo user pages kosong, kalau project pages pakai /namarepo

repository: kodeprofit/kodeprofit.github.io

# ---------------------------------------------
# Author
# ---------------------------------------------
author:
  name: "Tim Kode Profit"
  email: "ringinbambu@gmail.com"
  url: "https://kodeprofit.github.io/about"

# ---------------------------------------------
# Theme
# ---------------------------------------------
remote_theme: mmistakes/minimal-mistakes

# ---------------------------------------------
# Plugins
# ---------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache

# ---------------------------------------------
# SEO dan analytics
# ---------------------------------------------
google_analytics: UA-XXXXXXXXX-Y  # Ganti dengan kode asli jika pakai GA
lang: id
logo: /assets/images/logo.png
social:
  links:
    - "https://instagram.com/kodeprofit"
    - "https://t.me/kodeprofit"
    - "https://github.com/kodeprofit"

# ---------------------------------------------
# Default values
# ---------------------------------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author: "Tim Kode Profit"
      read_time: true
      comments: true
      share: true
      related: true

# ---------------------------------------------
# Navigation
# ---------------------------------------------
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
  - title: "Tools"
    url: "/tools/"
  - title: "Contact"
    url: "/contact/"

# ---------------------------------------------
# Social
# ---------------------------------------------
github_username: kodeprofit
instagram_username: kodeprofit
telegram_username: kodeprofit

# ---------------------------------------------
# Pagination
# ---------------------------------------------
paginate: 5
paginate_path: "/page:num/"

# ---------------------------------------------
# Permalink
# ---------------------------------------------
permalink: /:categories/:title/

# ---------------------------------------------
# Build settings
# ---------------------------------------------
markdown: kramdown
highlighter: rouge

# ---------------------------------------------
# Exclude / include
# ---------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

include:
  - _pages
  - robots.txt

# ---------------------------------------------
# Other options (optional)
# ---------------------------------------------
timezone: Asia/Jakarta

# Tagline
tagline: "Puncak dan lembah hanyalah bagian dari perjalanan — yang penting, kita tetap profit! 💹🚀"
